kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    protocol: TCP
    listenAddress: "0.0.0.0"
    hostPort: 30001
- role: worker
